#!/bin/bash






# -------- DECLARATIONS --------

#exit on error
set -e

#current execution directory
CXD=$(dirname $(realpath $0))
pCXD=$(dirname $CXD)

#input/output
TMP=$pCXD/out/tmp
APP=$pCXD/out/app

#get into main project directory
cd $pCXD






# -------- INITIALIZATION --------

#remove previous generations
rm --recursive --force $TMP $APP
mkdir --parents        $TMP $APP






# -------- EXECUTION --------

#object compilation
echo "Compiling main object file..."
cc -std=c11 -g -fno-common -Wall -Wno-switch -c -o $TMP/chibincc.o $pCXD/src/entry_point.c

#executable
echo "Compiling final executable..."
cc -std=c11 -g -fno-common -Wall -Wno-switch -o $APP/chibincc $TMP/chibincc.o

#end message
echo "Compilation done."
