#!/bin/bash



# -------- DECLARATIONS --------

#exit on error
set -e

#current execution directory
CXD=$(dirname $(realpath $0))
pCXD=$(dirname $CXD)

#input/output
SRC=$pCXD/src
TMP=$pCXD/out/tmp
APP=$pCXD/out/app

#get into main project directory
cd $pCXD






# -------- TOOLS --------

#mkdir_ifnotexist <<<<<<<<<<<<<<<<<<<<< should be an STDZ function
function mkdir_ifnotexist() {
	for a in $@; do
		if [[ ! -d $a ]]; then
			mkdir $a
		fi
	done
}






# -------- EXECUTION --------

#clean previous generation
if [[ -f $APP/chibicc ]]; then
	rm $APP/chibicc
fi
mkdir_ifnotexist $pCXD/out $TMP $APP

#object compilation
echo "Compiling main object file..."
cc -std=c11 -g -fno-common -Wall -Wno-switch -c -o $TMP/chibicc.o $SRC/entry_point.c

#executable
echo "Compiling final executable..."
cc -std=c11 -g -fno-common -Wall -Wno-switch -o $APP/chibicc $TMP/chibicc.o

#end message
echo "Compilation done."
